### ISSUE TITLE
Find better source for listing agenda items

### ISSUE THREAD

**Issue by garobrik** [IlyaKreynin/citizen-dashboard#11]
Currently we use the CSV voting records from Open Data TO for populating our database of agenda items. This might be incompatible with the product goal of notifying users of upcoming agenda items _before_ they're voted on. 

Unfortunately there might not be any other officially published listings of agenda items, but we're needing to scrape unofficially published data anyway to get the full agenda item description.

The goal for this task is to figure out which pages or API endpoints we can query to get a full listing of agenda items and their content. 

Step 1 should be to document the underlying conceptual data model of how agenda items, committees, meetings are related and what content we are interested in scraping from those entities.

Step 2 will be to document a set of endpoints that can be queried to fill out all that data.

Goals:
- don't overload any city APIs
- be able to provide updates within a day of the info being available online (based on assumption that things sometimes get posted only 5 business days in advance of people possibly needing to take action on them)

There is a working assumption that agenda items do not change frequently or at all, so we don't need to rescrape them for updates. Bonus points for validating this assumption.

**Comment by garobrik** [comment]
@BugsAplenty does this all sound accurate? this would be the most interesting backend thing for me to look into if i do do any backend work

**Comment by BugsAplenty** [comment]
This is perfectly and succinctly explained. It would be extremely favorable for us to find a way to get the data gracefully. And also, you're on! :sunglasses:

**Comment by BugsAplenty** [comment]
@shrouxm given your recent unveiling of that wonderful API, I think we can close this and create an issue for integrating the new API into our codebase. It seems to be superior in every way to the current way of doing things. What do you say?
