### ISSUE TITLE
Restructure project to deploy as kubernetes cluster

### ISSUE THREAD

**Issue by BugsAplenty** [IlyaKreynin/citizen-dashboard#9]
Currently the project structure is subdivided as frontend and backend when in fact we're aiming to create a cloud-based kubernetes cluster, which will require rearranging the various utilities within the codebase in accordance with that paradigm.

**Comment by korabel** [comment]
Created and pushed first set of changes that includes:
1. Deployment github action
2. data-fetch service
3. data-store service
4. folder structure refactor: all in services folder

**Comment by BugsAplenty** [comment]
I think we can close this one.
